version: "3"
services:
  php:
    # імʼя контейнеру, яке будемо використовувати при вході на контейнер
    container_name: php_pro_11
    build:
      context: ./
      # посилання на докерфайл з налаштуванням контейнеру
      dockerfile: "docker/configs/php/Dockerfile"
    # встановлюємо змінні оточення
    environment:
      XDEBUG_CONFIG: "remote_host={{YOUR_IP_ADDRESS}}"
      PHP_IDE_CONFIG: "serverName=docker"
    # прописуємо синхронізацію директорій
    volumes:
      - ./:/srv/src/php_pro
    links:
      - db_mysql

  db_mysql:
    image: mysql:latest
    container_name: php_pro_1_mysql1
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: php_pro
      MYSQL_USER: vitor
      MYSQL_PASSWORD: pass4vitor
    volumes:
      - ./docker/databases/mysql_dump:/docker-entrypoint-initdb.d
  nginx:
    image: nginx:latest
    container_name: php_pro_1_nginx1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/srv/src/php_pro
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    links:
      - php